# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_false', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleQuestion',
            fields=[
                ('tf_question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='true_false.TF_Question')),
                ('related_word_id', models.IntegerField()),
            ],
            bases=('true_false.tf_question',),
        ),
    ]
