# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('article', models.CharField(max_length=3)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articlequestion',
            name='article',
            field=models.CharField(default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='articlequestion',
            name='related_word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Word', verbose_name='Question'),
        ),
    ]
