# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20170109_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='article',
            field=models.CharField(choices=[('der', 'der'), ('die', 'die'), ('das', 'das')], max_length=3),
        ),
    ]
